config/routes.rb
Rails.application.routes.draw do

  resource :support, only: [:show]
  resource :help, only: [:show]
  resources :demo_greeting, only: [:show]
  resource :demo, only: [:show] do
    member do
      post :options, :reminder
      get :confirmation, :cancelation
    end
  end

  # mount SmsConfirm::Engine => "/r"

  root :to => "dashboard#index"

  get "onboarding.js" => "dashboard#onboarding"

  get "browser_not_supported" => "pages#browser_not_supported"

  devise_for :users, skip: [:sessions, :registrations]
  devise_scope :user do
    post 'sign_in', to: "sessions#create", as: :user_session
    get 'sign_in', to: "sessions#new", as: :new_user_session
    delete 'sign_out', to: "sessions#destroy", as: :destroy_user_session
    post 'register', to: "registrations#create", as: :user_registration
    get 'register', to: "registrations#new", as: :new_user_registration
    get "register/:package_code" => "registrations#new"
  end

  devise_for :admin

  authenticate :admin do
    ActiveAdmin.routes(self)
  end

  post "sms/reply" => "sms#reply", as: :sms_reply
  get "sms/test" => "sms#test"
  post "sms/callback" => "sms#callback", as: :sms_callback
  post "voice/reminder" => "voice#reminder", as: :voice_reminder
  post "voice/update" => "voice#update", as: :voice_update
  get "voice/confirmation" => "voice#confirmation", as: :voice_confirmation
  get "voice/cancelation" => "voice#cancelation", as: :voice_cancelation
  get "voice/callback" => "voice#callback", as: :voice_callback

  resource :subscription_plans, only: [:edit, :update]
  resource :payments, only: [:edit, :update]

  resources :users, only: [:index, :update, :show, :destroy] do
    member do
      put :toggle_status
      post :resend_invitation
    end
  end

  resources :schedules do
    resources :schedule_subscriptions
    resources :schedule_timings
    resources :scripts, only: [:index]
    scope module: 'schedules' do
      resource :options
    end
    namespace :script do
      resources :emails, only: [:update, :edit]
      resources :sms, only: [:update, :edit]
      resources :voice, only: [:update, :edit]
    end
    resource :caller_id do
      member do
        get :verification_check
        get :verified
      end
    end
  end

  post "caller_id_confirmations/:schedule_id" => "caller_id_confirmations#create", as: :caller_id_confirmations

  resources :clients
  get "clients/search/:name" => "clients#search", as: :search
  get "unsubscribe/:token" => "clients#unsubscribe", as: :unsubscribe
  get "clients/contact_fields/:id" => "clients#contact_fields", as: :contact_fields

  resources :events do
    resources :notes, only: [:create, :edit, :update, :destroy]
    member do
      get :confirm
      get :cancel
      get :showed
      get :no_show
    end

    resources :manual_triggers, only: [:index, :update], param: :action
  end

  resources :event_series

  post 'events/new' => 'events#new'

  resource :profile, only: [:edit, :update]
  resource :account, only: [:edit, :update, :destroy]
  resource :expire, only: [:edit, :update]

  resource :billing

  resource :stripe, only: [], format: true, :constraints => { :format => /xml/ } do
    post :charge
  end

  get "dashboard/index"

  get '/secret/exception/raiser' => 'test_exceptions#show'

  get '/reports' => 'reports#index'

end

app/controllers/expires_controller.rb
class ExpiresController < PublicController
  # layout 'settings'
  load_and_authorize_resource :current_account
  before_action :plans
  skip_before_filter :redirect_trial_accounts
  before_filter :reject_trial_accounts

  def edit
  end

  def update
    if current_account.update_attributes(account_params)
      redirect_to root_path
    else
      render :edit
    end
  end

 private

  def account_params
    params.require(:account).permit(:stripe_token, :last_4_digits, :subscription_plan_id)
  end

  def plans
    @plans = SubscriptionPlan.all
  end

  def reject_trial_accounts
    redirect_to root_path unless current_account.needs_subscription_info?
  end

end

app/views/expires/edit.html.haml
- content_for :header do
  = javascript_include_tag "https://js.stripe.com/v2"
  = javascript_tag "Stripe.setPublishableKey('#{Rails.configuration.stripe[:publishable_key]}');"

.card
  %h3= t(".heading")
  .tab-content
    .card-inner.large-padding
      = form_for :account, method: :put, url: expire_path, html: {class: "form-horizontal", role: "form"} do |f|
        = f.hidden_field :stripe_token, id: "user_account_attributes_stripe_token"
        = f.hidden_field :last_4_digits, id: "user_account_attributes_last_4_digits"
        #credit-card
          %h2= t('.thank_you')
          %h4= t('.info', trial_days: current_account.trial_period_end_date_on_days)
          = render partial: "payments/credit_card"
        .form-group
          = label_tag :subscription_plan_id, "Subscription Plan", class: "col-sm-4 control-label"
          .row
            .col-sm-7
              %table.table.table-no-border
                - for plan in @plans
                  %tr
                    %td
                      = f.radio_button :subscription_plan_id, plan.id
                      = f.label :subscription_plan_id, plan.name, value: plan.id
        .form-group
          .col-sm-4.col-sm-offset-4
            = f.submit(class: "btn btn-primary")
            = link_to "Cancel", billing_path