config/routes.rb
Rails.application.routes.draw do

  resource :support, only: [:show]
  resource :help, only: [:show]
  resources :demo_greeting, only: [:show]
  resource :demo, only: [:show] do
    member do
      post :options, :reminder
      get :confirmation, :cancelation
    end
  end

  # mount SmsConfirm::Engine => "/r"

  root :to => "dashboard#index"

  get "onboarding.js" => "dashboard#onboarding"

  get "browser_not_supported" => "pages#browser_not_supported"

  devise_for :users, skip: [:sessions, :registrations]
  devise_scope :user do
    post 'sign_in', to: "sessions#create", as: :user_session
    get 'sign_in', to: "sessions#new", as: :new_user_session
    delete 'sign_out', to: "sessions#destroy", as: :destroy_user_session
    post 'register', to: "registrations#create", as: :user_registration
    get 'register', to: "registrations#new", as: :new_user_registration
    get "register/:package_code" => "registrations#new"
  end

  devise_for :admin

  authenticate :admin do
    ActiveAdmin.routes(self)
  end

  post "sms/reply" => "sms#reply", as: :sms_reply
  get "sms/test" => "sms#test"
  post "sms/callback" => "sms#callback", as: :sms_callback
  post "voice/reminder" => "voice#reminder", as: :voice_reminder
  post "voice/update" => "voice#update", as: :voice_update
  get "voice/confirmation" => "voice#confirmation", as: :voice_confirmation
  get "voice/cancelation" => "voice#cancelation", as: :voice_cancelation
  get "voice/callback" => "voice#callback", as: :voice_callback

  resource :subscription_plans, only: [:edit, :update]
  resource :payments, only: [:edit, :update]

  resources :users, only: [:index, :update, :show, :destroy] do
    member do
      put :toggle_status
      post :resend_invitation
    end
  end

  resources :schedules do
    resources :schedule_subscriptions
    resources :schedule_timings
    resources :scripts, only: [:index]
    scope module: 'schedules' do
      resource :options
    end
    namespace :script do
      resources :emails, only: [:update, :edit]
      resources :sms, only: [:update, :edit]
      resources :voice, only: [:update, :edit]
    end
    resource :caller_id do
      member do
        get :verification_check
        get :verified
      end
    end
  end

  post "caller_id_confirmations/:schedule_id" => "caller_id_confirmations#create", as: :caller_id_confirmations

  resources :clients
  get "clients/search/:name" => "clients#search", as: :search
  get "unsubscribe/:token" => "clients#unsubscribe", as: :unsubscribe
  get "clients/contact_fields/:id" => "clients#contact_fields", as: :contact_fields

  resources :events do
    resources :notes, only: [:create, :edit, :update, :destroy]
    member do
      get :confirm
      get :cancel
      get :showed
      get :no_show
    end

    resources :manual_triggers, only: [:index, :update], param: :action
  end

  resources :event_series

  post 'events/new' => 'events#new'

  resource :profile, only: [:edit, :update]
  resource :account, only: [:edit, :update, :destroy]
  resource :expire, only: [:edit, :update]

  resource :billing

  resource :stripe, only: [], format: true, :constraints => { :format => /xml/ } do
    post :charge
  end

  get "dashboard/index"

  get '/secret/exception/raiser' => 'test_exceptions#show'

  get '/reports' => 'reports#index'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :account
  has_one :caller_id, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :clients, through: :events
  has_many :schedule_subscriptions, dependent: :destroy
  has_many :schedule_timings, -> { order "created_at" }, dependent: :destroy
  has_many :script_groups, dependent: :destroy
  has_many :email_scripts, through: :script_groups
  has_many :sms_scripts, through: :script_groups
  has_many :voice_scripts, through: :script_groups
  has_many :subscribers, source: :user, through: :schedule_subscriptions, extend: Concerns::UserNotificationPreferences

  VALID_LENGTH = (5..150).to_a
  VALID_FREQUENCY = [5, 10, 15, 20, 30, 40, 50, 60, 70, 80]
  VALID_HOURS = (0..23).to_a

  DEFAULT_VALUES = { name: I18n.t('models.schedule.default_value') }

  REMINDER_PREFERENCES = {EMAIL: 1, SMS: 2, VOICE: 3}
  REMINDER_CODE_MAP = Hash[REMINDER_PREFERENCES.to_a.map(&:reverse)]

  validates_presence_of :name
  validates_presence_of :starts_at, :ends_at, :frequency, :length
  validates :starts_at, :ends_at, inclusion: { in: VALID_HOURS }, allow_nil: true
  validates :frequency, inclusion: { in: VALID_FREQUENCY }, allow_nil: true
  validates :length, inclusion: { in: VALID_LENGTH }, allow_nil: true
  validates :length, :frequency, :length, :ends_at, :starts_at, numericality: true, allow_nil: true

  before_create :build_default_associations!


  def default_timing
    schedule_timings.detect(&:default)
  end

  delegate :number, to: :caller_id, prefix: true, allow_nil: true

  # script group needs a default attribute
  def default_script_group
    script_groups.first
  end

  def build_default_associations!
    script_group = self.script_groups.build(ScriptGroup.default_values)
    schedule_timing = self.schedule_timings.build(ScheduleTiming.default_values)
    script_group.build_email_script(Script::Email.default_values(account))
    script_group.build_sms_script(Script::Sms.default_values(account))
    script_group.build_voice_script(Script::Voice.default_values(account))
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < PublicController
  authorize_resource

  respond_to :html

  layout 'settings'

  def new
    @schedule = current_account.schedules.build
    respond_with(@schedule)
  end

  def create
    @schedule = current_account.schedules.build(permitted_params)
    respond_with @schedule do |format|
      if @schedule.save
        flash[:notice] = t('.success')
        format.html { redirect_to edit_schedule_path(@schedule) }
      else
        format.html { render action: :new }
      end
    end
  end

  def index
    schedules
  end

  def edit
    schedule
  end

  def show
    schedule
  end

  def update
    if schedule.update_attributes(permitted_params)
      flash[:notice] = t('.success')
    end
    respond_with(schedule, location: edit_schedule_path(schedule))
  end

  def destroy
    flash[:notice] = t('.success') if schedule.destroy
    respond_with(schedule)
  end

  private

  def permitted_params
    params.require(:schedule).permit(:name, :starts_at, :ends_at, :frequency, :length, :notes_enabled, :business_days => [], :reminder_preferences => [])
  end

  def schedules
    @schedules ||= current_account.schedules.page(params[:page]).per(10)
  end

  def schedule
    @schedule ||= current_account.schedules.find(params[:id])
  end

end

app/helpers/schedules/options_helper.rb
module Schedules::OptionsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper

  def frequency_options
    scope = 'helpers.schedules_helper.frequency_options'
    {
      t('minutes', scope: scope, min: 5) => 5,
      t('minutes', scope: scope, min: 10) => 10,
      t('minutes', scope: scope, min: 15) => 15,
      t('minutes', scope: scope, min: 20) => 20,
      t('minutes', scope: scope, min: 30) => 30,
      t('hour', scope: scope) => 60
    }
  end

  def length_options
    scope = 'helpers.schedules_helper.length_options'
    %w(5 10 15 20 25 30 35 40 45 50 55 60 90 120 150).inject({}) do |hash, arr|
      hash.merge!(t('minutes', scope: scope, min: arr) => arr.to_i)
    end
  end

  def business_days_options
    t('date.abbr_day_names').each_with_index.to_h
  end

  def reminder_preference_options
    Schedule::REMINDER_PREFERENCES
  end

  def is_active?(controller, action)
    t('helpers.schedules_helper.is_active') if (controller_name == controller && action_name == action)
  end

end

app/views/schedules/_form.html.haml
= simple_form_for @schedule, wrapper: :bootstrap_horizontal, html: {class: 'form-horizontal schedule-form', role: 'form'} do |f|

  = f.input :name, required: true, hint: t('.name_hint')

  .form-group
    = f.label :schedulable_hours, t('.schedulable_hours'), required: true, class: "control-label col-xs-3 col-sm-3 col-md-3 col-lg-3"
    .col-lg-3
      = f.select :starts_at, hour_options, {}, class: 'form-control'
    .col-lg-3
      = f.select :ends_at, hour_options, {}, class: 'form-control'
    .help-block.schedulable-hours.col-lg-offset-3
      .added-margin
        = t('.hours_hint')

  = f.input :frequency, collection: frequency_options, hint: t(".frequency_hint", event_name: event_name.pluralize)
  = f.input :length, collection: length_options, hint: t(".length_hint", event_name: event_name.pluralize)
  .form-group
    = f.label :business_days, class: "col-xs-3 col-sm-3 col-md-3 col-lg-3"
    .col-xs-7.col-sm-7.col-md-7.col-lg-7
      - business_days_options.each do |day, value|
        %span{class: 'checkbox checkbox-inline'}
          = f.label :business_days, value: value do
            = f.check_box :business_days, { multiple: true, checked: f.object.business_days.include?(value.to_s) }, value, nil
            = day
    .help-block.business-days.col-lg-offset-3
      .added-margin
        = t(".day_hint")

  .form-group
    = f.label :reminder_preferences, class: "col-xs-3 col-sm-3 col-md-3 col-lg-3"
    .col-xs-9.col-sm-9.col-md-9.col-lg-9
      - reminder_preference_options.each do |option, value|
        %span{class: 'checkbox checkbox-inline'}
          = f.label :reminder_preference, value: value do
            = f.check_box :reminder_preferences, {multiple: true, checked: f.object.reminder_preferences.include?(value.to_s)}, value, nil
            = option.to_s.dasherize
    .help-block.col-lg-offset-3
      .added-margin
        = t('.communication_hint')
  .form-group
    = f.label :notes_enabled, class: "col-xs-3 col-sm-3 col-md-3 col-lg-3"
    .col-xs-9.col-sm-9.col-md-9.col-lg-9
      = f.check_box :notes_enabled
      = t('.notes_enabled_hint')

  = decorated_submit(f)

app/views/schedules/_options.html.haml
.bs-callout.bs-callout-danger
  %h4= t('.heading')
  %p= t('.info')

  = link_to t('.delete_schedule_btn'), schedule_path, class: "btn btn-danger btn-lg", method: "delete", confirm: t('.confirm_msg')

app/views/schedules/edit.html.haml
.card
  = render 'shared/schedule_tabs'

  / Tab panes
  .tab-content
    .tab-pane#settings.active
      .card-inner.large-padding
        = render 'form'

app/views/schedules/index.html.haml
.card
  %h3= t(".schedules")

  .tab-content
    .card-inner.large-padding
      %table
        - @schedules.each do |schedule|
          %tr
            %td
              %strong= link_to_with_icon schedule.name, edit_schedule_path(schedule), "calendar"

      %br
      = link_to t('.add_new_schedule'), new_schedule_path, class: "btn btn-primary"

      = link_to t('.unavailable_mode'), root_path(unavailable_mode: unavailable_mode? ? false : true), class: "btn btn-warning"

app/views/schedules/new.html.haml
%h3= t('.heading')

.tab-content
  .card-inner.large-padding
    = render 'form'

app/views/schedules/show.html.haml
.card
  = render 'shared/schedule_tabs'
  .tab-content
    .tab-pane#settings.active
      .card-inner.large-padding
        .bs-callout.bs-callout-danger
          %h4= t('.heading')
          %p= t('.info')

          = link_to t('.delete_schedule_btn'), schedule_path(@schedule), class: "btn btn-danger btn-lg", method: "delete", confirm: t('.confirm_msg')