config/routes.rb
Rails.application.routes.draw do

  resource :support, only: [:show]
  resource :help, only: [:show]
  resources :demo_greeting, only: [:show]
  resource :demo, only: [:show] do
    member do
      post :options, :reminder
      get :confirmation, :cancelation
    end
  end

  # mount SmsConfirm::Engine => "/r"

  root :to => "dashboard#index"

  get "onboarding.js" => "dashboard#onboarding"

  get "browser_not_supported" => "pages#browser_not_supported"

  devise_for :users, skip: [:sessions, :registrations]
  devise_scope :user do
    post 'sign_in', to: "sessions#create", as: :user_session
    get 'sign_in', to: "sessions#new", as: :new_user_session
    delete 'sign_out', to: "sessions#destroy", as: :destroy_user_session
    post 'register', to: "registrations#create", as: :user_registration
    get 'register', to: "registrations#new", as: :new_user_registration
    get "register/:package_code" => "registrations#new"
  end

  devise_for :admin

  authenticate :admin do
    ActiveAdmin.routes(self)
  end

  post "sms/reply" => "sms#reply", as: :sms_reply
  get "sms/test" => "sms#test"
  post "sms/callback" => "sms#callback", as: :sms_callback
  post "voice/reminder" => "voice#reminder", as: :voice_reminder
  post "voice/update" => "voice#update", as: :voice_update
  get "voice/confirmation" => "voice#confirmation", as: :voice_confirmation
  get "voice/cancelation" => "voice#cancelation", as: :voice_cancelation
  get "voice/callback" => "voice#callback", as: :voice_callback

  resource :subscription_plans, only: [:edit, :update]
  resource :payments, only: [:edit, :update]

  resources :users, only: [:index, :update, :show, :destroy] do
    member do
      put :toggle_status
      post :resend_invitation
    end
  end

  resources :schedules do
    resources :schedule_subscriptions
    resources :schedule_timings
    resources :scripts, only: [:index]
    scope module: 'schedules' do
      resource :options
    end
    namespace :script do
      resources :emails, only: [:update, :edit]
      resources :sms, only: [:update, :edit]
      resources :voice, only: [:update, :edit]
    end
    resource :caller_id do
      member do
        get :verification_check
        get :verified
      end
    end
  end

  post "caller_id_confirmations/:schedule_id" => "caller_id_confirmations#create", as: :caller_id_confirmations

  resources :clients
  get "clients/search/:name" => "clients#search", as: :search
  get "unsubscribe/:token" => "clients#unsubscribe", as: :unsubscribe
  get "clients/contact_fields/:id" => "clients#contact_fields", as: :contact_fields

  resources :events do
    resources :notes, only: [:create, :edit, :update, :destroy]
    member do
      get :confirm
      get :cancel
      get :showed
      get :no_show
    end

    resources :manual_triggers, only: [:index, :update], param: :action
  end

  resources :event_series

  post 'events/new' => 'events#new'

  resource :profile, only: [:edit, :update]
  resource :account, only: [:edit, :update, :destroy]
  resource :expire, only: [:edit, :update]

  resource :billing

  resource :stripe, only: [], format: true, :constraints => { :format => /xml/ } do
    post :charge
  end

  get "dashboard/index"

  get '/secret/exception/raiser' => 'test_exceptions#show'

  get '/reports' => 'reports#index'

end

app/views/shared/_analytics.html.haml
- if Rails.env == 'production'
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-54330390-1', 'auto');
    ga('require', 'displayfeatures');
    ga('send', 'pageview');
    ga('set', 'contentGroup1', 'Webapp');

app/views/shared/_favicons.html.haml
/ For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
/ Size should be 57 x 57 pixels
= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
/ For first- and second-generation iPad:
/ Size should be 72 x 72 pixels
= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
/ For iPhone with high-resolution Retina display:
/ Size should be 114 x 114 pixels
= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
/ For third-generation iPad with high-resolution Retina display:
/ Size should be 144 x 144 pixels
= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
/ For all other devices
/ Size should be 32 x 32 pixels
= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

app/views/shared/_form_errors.html.haml
- if object && object.errors.any?
  #error_explanation
    %p= "Whoops, #{object.errors.full_messages.to_sentence.downcase}"

app/views/shared/_kissmetrics.html.haml
- if Rails.env == 'production'
  :javascript
    var _kmq = _kmq || [];
    var _kmk = _kmk || '2b27831d2c60e2933d6f76673e3b096cfe92dab8';
    function _kms(u){
      setTimeout(function(){
        var d = document, f = d.getElementsByTagName('script')[0],
        s = d.createElement('script');
        s.type = 'text/javascript'; s.async = true; s.src = u;
        f.parentNode.insertBefore(s, f);
      }, 1);
    }
    _kms('//i.kissmetrics.com/i.js');
    _kms('//doug1izaerwt3.cloudfront.net/' + _kmk + '.1.js');

app/views/shared/_logged_navigation.html.haml
- if current_user
  %ul.nav.navbar-nav
    %li{:class => 'dropdown'}
      %a.dropdown-toggle{href: schedules_path, 'data-toggle' => 'dropdown'}
        = t('.schedules')
        %b{class: 'caret'}
      %ul{class: 'dropdown-menu'}
        - if current_user.admin?
          %li
            = link_to t('.manage'), schedules_path
          %li{class: 'divider'}
        %li
          = link_to t('.all_schedules'), root_path(schedule: 'all')
          - current_account.schedules.order('name').each do |schedule|
            = link_to schedule.name, root_path(schedule: schedule.id)

    %li= link_to "#{client_name.capitalize.pluralize}", "/clients"
    %li= link_to "Reports", "/reports"
    %li= link_to "Support", "https://practicaldesk.freshdesk.com"

  %ul.nav.navbar-nav.navbar-right
    -if current_account.trial_about_to_expire?
      .navbar-text.alert.alert-warning
        %strong= t('.trial_perior_expiring_title')
        = t('.trial_perior_expiring', trial_days: current_account.trial_period_end_date_on_days )
    %li{:class => 'dropdown'}
      %a.dropdown-toggle{href: '#', 'data-toggle' => 'dropdown'}
        = current_user.name
        %b{class: 'caret'}
      %ul{class: 'dropdown-menu'}
        %li
          = link_to t('.my_profile'), edit_profile_path
        %li
          = link_to t('.account_settings'), edit_account_path
        %li
          = link_to t('.logout'), destroy_user_session_path, method: "delete"

app/views/shared/_registration_navigation.html.haml
%ul.registration-nav.navbar-right
  %li= link_to "See pricing & start free trial", new_user_registration_path
  %li= link_to "Support", "https://practicaldesk.freshdesk.com"
  %li= link_to "Log in to an existing account", new_user_session_path, class: "btn btn-success"

app/views/shared/_schedule_tabs.html.haml
%h3=h @schedule.name

%ul.nav.nav-tabs
  %li{class: is_active?('schedules', 'edit') }
    = link_to t('.settings'), edit_schedule_path(@schedule)
  %li{class: is_active?('schedule_subscriptions', 'index') }
    = link_to t('.subscriptions'), schedule_schedule_subscriptions_path(@schedule)
  %li{class: is_active?('schedule_timings', 'index') }
    = link_to t('.timing'), schedule_schedule_timings_path(@schedule)
  %li{class: is_active?('scripts', 'index') }
    = link_to t('.scripts'), schedule_scripts_path(@schedule)
  %li{class: is_active?('caller_ids', 'show') }
    = link_to t('.caller_id'), schedule_caller_id_path(@schedule)
  %li{class: is_active?('schedules', 'show') }
    = link_to t('.options'), schedule_path(@schedule)